path = 'lib/services/vector_store.dart'
text = open(path, 'r', encoding='utf-8').read()
text = text.replace('Future<void> save() async {', 'Future<void> save() async { print("vs1");')
text = text.replace('final tmp = File(\'${f.path}.tmp\');', 'print("vs2"); final tmp = File(\'${f.path}.tmp\');')
text = text.replace('final data = jsonEncode(payload);', 'print("vs3"); final data = jsonEncode(payload);')
text = text.replace('await tmp.writeAsString(data, flush: true);', 'print("vs4"); await tmp.writeAsString(data, flush: true);')
text = text.replace('if (await f.exists()) {', 'print("vs5"); if (await f.exists()) {')
text = text.replace('await f.delete();', 'print("vs6"); await f.delete(); print("vs7");')
text = text.replace('await tmp.rename(f.path);', 'print("vs8"); await tmp.rename(f.path); print("vs9");')
open(path, 'w', encoding='utf-8').write(text)
print('Injected vstore')
