// lib/models/health_record.dart
//
// Phase 6.7 (v2.3) — Health record model.
// Stored inside VectorStore under the 'Health' collection. Each record is
// serialized to JSON in DocChunk.text; embeddings stay empty in MVP and
// can be back-filled by PersonalRagService later (same pattern as
// Expense/Contact).
//
// Every measurement field is nullable because a single entry may capture
// just one metric (e.g. user logs only weight today, only BP tomorrow).
// At least one measurement is enforced at the UI layer, not here.

import 'dart:convert';

class HealthRecord {
  /// Stable unique id. Generated by HealthController on first save.
  final String id;

  /// When the measurement was taken (NOT when entered into the app).
  final DateTime date;

  /// Body weight in kilograms.
  final double? weight;

  /// Blood pressure — systolic / diastolic in mmHg.
  final int? systolic;
  final int? diastolic;

  /// Resting heart rate in beats per minute.
  final int? heartRate;

  /// Daily step count.
  final int? steps;

  /// Hours slept (decimals allowed; e.g. 7.5).
  final double? sleepHours;

  /// Free-text notes ('felt tired', 'after run', etc.).
  final String notes;

  /// Free-text tags ('post-workout', 'morning', ...).
  final List<String> tags;

  /// When the record was entered into the app.
  final DateTime dateAdded;

  /// Origin: 'manual' / 'imported' / 'apple_health' / ...
  final String source;

  const HealthRecord({
    this.id = '',
    required this.date,
    this.weight,
    this.systolic,
    this.diastolic,
    this.heartRate,
    this.steps,
    this.sleepHours,
    this.notes = '',
    this.tags = const [],
    required this.dateAdded,
    this.source = 'manual',
  });

  /// True if at least one measurement field is non-null.
  bool get hasAnyMeasurement =>
      weight != null ||
      systolic != null ||
      diastolic != null ||
      heartRate != null ||
      steps != null ||
      sleepHours != null;

  Map<String, dynamic> toJson() => {
        'id': id,
        'date': date.toIso8601String(),
        'weight': weight,
        'systolic': systolic,
        'diastolic': diastolic,
        'heartRate': heartRate,
        'steps': steps,
        'sleepHours': sleepHours,
        'notes': notes,
        'tags': tags,
        'dateAdded': dateAdded.toIso8601String(),
        'source': source,
      };

  factory HealthRecord.fromJson(Map<String, dynamic> j) => HealthRecord(
        id: (j['id'] as String?) ?? '',
        date: DateTime.parse(j['date'] as String),
        weight: (j['weight'] as num?)?.toDouble(),
        systolic: (j['systolic'] as num?)?.toInt(),
        diastolic: (j['diastolic'] as num?)?.toInt(),
        heartRate: (j['heartRate'] as num?)?.toInt(),
        steps: (j['steps'] as num?)?.toInt(),
        sleepHours: (j['sleepHours'] as num?)?.toDouble(),
        notes: (j['notes'] as String?) ?? '',
        tags: (j['tags'] as List?)?.cast<String>() ?? const [],
        dateAdded: DateTime.parse(j['dateAdded'] as String),
        source: (j['source'] as String?) ?? 'manual',
      );

  String encode() => jsonEncode(toJson());
  static HealthRecord decode(String raw) =>
      HealthRecord.fromJson(jsonDecode(raw) as Map<String, dynamic>);

  /// Searchable text — structured measurement labels so RAG queries like
  /// "weight last month" or "blood pressure" can match on substring.
  String toSearchText() {
    final parts = <String>[];
    if (weight != null) parts.add('weight ${weight}kg');
    if (systolic != null && diastolic != null) {
      parts.add('blood pressure $systolic/$diastolic');
    }
    if (heartRate != null) parts.add('heart rate $heartRate bpm');
    if (steps != null) parts.add('$steps steps');
    if (sleepHours != null) parts.add('sleep ${sleepHours}h');
    if (notes.isNotEmpty) parts.add(notes);
    parts.addAll(tags);
    return parts.join(' ');
  }

  HealthRecord copyWith({
    String? id,
    DateTime? date,
    double? weight,
    bool clearWeight = false,
    int? systolic,
    bool clearSystolic = false,
    int? diastolic,
    bool clearDiastolic = false,
    int? heartRate,
    bool clearHeartRate = false,
    int? steps,
    bool clearSteps = false,
    double? sleepHours,
    bool clearSleepHours = false,
    String? notes,
    List<String>? tags,
    DateTime? dateAdded,
    String? source,
  }) {
    return HealthRecord(
      id: id ?? this.id,
      date: date ?? this.date,
      weight: clearWeight ? null : (weight ?? this.weight),
      systolic: clearSystolic ? null : (systolic ?? this.systolic),
      diastolic: clearDiastolic ? null : (diastolic ?? this.diastolic),
      heartRate: clearHeartRate ? null : (heartRate ?? this.heartRate),
      steps: clearSteps ? null : (steps ?? this.steps),
      sleepHours:
          clearSleepHours ? null : (sleepHours ?? this.sleepHours),
      notes: notes ?? this.notes,
      tags: tags ?? this.tags,
      dateAdded: dateAdded ?? this.dateAdded,
      source: source ?? this.source,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! HealthRecord) return false;
    return id == other.id &&
        date == other.date &&
        weight == other.weight &&
        systolic == other.systolic &&
        diastolic == other.diastolic &&
        heartRate == other.heartRate &&
        steps == other.steps &&
        sleepHours == other.sleepHours &&
        notes == other.notes &&
        _listEq(tags, other.tags) &&
        dateAdded == other.dateAdded &&
        source == other.source;
  }

  @override
  int get hashCode => Object.hash(
        id,
        date,
        weight,
        systolic,
        diastolic,
        heartRate,
        steps,
        sleepHours,
        notes,
        Object.hashAll(tags),
        dateAdded,
        source,
      );

  static bool _listEq(List<String> a, List<String> b) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
}

/// Aggregated stats for a date-bounded slice of HealthRecord history.
class HealthStats {
  const HealthStats({
    required this.recordCount,
    required this.weightCount,
    required this.avgWeight,
    required this.minWeight,
    required this.maxWeight,
    required this.bloodPressureCount,
    required this.avgSystolic,
    required this.avgDiastolic,
    required this.heartRateCount,
    required this.avgHeartRate,
    required this.stepsCount,
    required this.totalSteps,
    required this.sleepCount,
    required this.avgSleepHours,
  });

  final int recordCount;

  final int weightCount;
  final double? avgWeight;
  final double? minWeight;
  final double? maxWeight;

  final int bloodPressureCount;
  final double? avgSystolic;
  final double? avgDiastolic;

  final int heartRateCount;
  final double? avgHeartRate;

  final int stepsCount;
  final int totalSteps;

  final int sleepCount;
  final double? avgSleepHours;

  bool get isEmpty => recordCount == 0;
}
